Repository mysociety/fixmystreet, pull requests merged in 2018-08, with the labels that each got.

#2196 allow inspector to drag pin after opening from around page
  CHANGELOG.md
  web/cobrands/fixmystreet/fixmystreet.js
  web/js/map-OpenLayers.js
Labels: Reviewed

#2198 "Report another problem here" button on confirmation page
  CHANGELOG.md
  templates/web/base/tokens/confirm_problem.html
  web/cobrands/sass/_base.scss
Labels: Reviewed

#2200 [Buckinghamshire] Update flytipping handling.
  perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
  perllib/FixMyStreet/SendReport/Email.pm
  perllib/FixMyStreet/SendReport/Open311.pm
  t/Mock/MapIt.pm
  t/cobrand/bucks.t
  web/cobrands/buckinghamshire/assets.js
Labels: Reviewing

#2218 /_dev confirmation pages
  CHANGELOG.md
  perllib/FixMyStreet/App/Controller/Auth.pm
  perllib/FixMyStreet/App/Controller/Contact.pm
  perllib/FixMyStreet/App/Controller/Develop.pm
  perllib/FixMyStreet/App/Controller/Questionnaire.pm
  perllib/FixMyStreet/App/Controller/Report/New.pm
  perllib/FixMyStreet/App/Controller/Tokens.pm
  t/app/controller/develop.t
  templates/web/base/develop/index.html
Labels: Reviewing

#2214 Add cobrand hook for disallowing updates on problems
  CHANGELOG.md
  perllib/FixMyStreet/App/Controller/Report/Update.pm
  t/app/controller/report_updates.t
  templates/web/base/report/display.html
  templates/web/base/report/update-form.html
Labels: Reviewed

#2219 [UK] utility script to generate stats for Defra
  bin/fixmystreet.com/defra_stats
Labels: In progress
