Repository mysociety/fixmystreet, pull requests merged in 2019-01, with the labels that each got.

#2363 add private only report filter
  CHANGELOG.md
  docs/_includes/admin-tasks-content.md
  perllib/FixMyStreet/App/Controller/Reports.pm
  perllib/FixMyStreet/DB/ResultSet/Problem.pm
  t/app/controller/around.t
  t/app/controller/reports.t
  templates/web/base/reports/_list-filters.html
Labels: Reviewed

#2364 add extra categories to demo site
  .cypress/cypress/integration/category_tests.js
  bin/fixmystreet.com/fixture
Labels: Reviewing

#2367 Swedish translations for v2.5
  locale/sv_SE.UTF-8/LC_MESSAGES/FixMyStreet.po
Labels: In progress

#2365 Stop double green pin on hover-end
  web/cobrands/fixmystreet/assets.js
Labels: Reviewing

#2377 Remove any use of `my $x if $foo`.
  CHANGELOG.md
  perllib/FixMyStreet/App/Controller/Photo.pm
  perllib/FixMyStreet/Cobrand/Default.pm
  perllib/FixMyStreet/Roles/Abuser.pm
  perllib/FixMyStreet/Script/Reports.pm
Labels: Reviewing

#2380 [Oxfordshire] length checking for names, emails and phone Nos
  perllib/FixMyStreet/Cobrand/Oxfordshire.pm
  t/app/controller/report_new.t
  templates/web/oxfordshire/footer_extra_js.html
  web/cobrands/fixmystreet-uk-councils/council_validation_rules.js
Labels: Reviewing

#2379 Moderation in front end updates
  CHANGELOG.md
  docs/_includes/admin-tasks-content.md
  perllib/FixMyStreet/App/Controller/Report.pm
  perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm
  t/app/controller/moderate.t
  templates/web/base/admin/report_edit.html
  templates/web/base/report/update.html
  templates/web/base/report/update/moderation.html
  templates/web/base/report/update/moderation_diff.html
  templates/web/base/report/update/moderation_meta.html
Labels: Reviewed

#2381 Allow state editing via moderation.
  CHANGELOG.md
  perllib/FixMyStreet/App/Controller/Moderate.pm
  t/app/controller/moderate.t
Labels: Reviewing
